# Generated by Django 4.2.5 on 2023-09-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_product_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Item",
        ),
    ]
